### ISSUE TITLE
Empty `p` elements on talk transcripts?

### ISSUE THREAD

**Issue by beep** [laras126/karenmcgrane#3]
Hey @laras126! On the talk transcripts ([e.g.](http://kmg-stage.bondartscience.com/talks/adaptive-content-context-and-controversy/)), each slide’s text seems like it has some extra whitespace above and below the text:

<img width="812" alt="" src="https://user-images.githubusercontent.com/124493/36305122-50a6af9a-12e0-11e8-9192-597f7bf757c1.png">

It looks like this is being caused by some empty paragraphs injected into each slide? I’ve highlighted the empty `<p></p>`s with a light blue here:

<img width="1066" alt="" src="https://user-images.githubusercontent.com/124493/36305165-74e2d726-12e0-11e8-9a9d-1a8d6f0cfd6b.png">

Is there any way to strip those out on the WordPress side?

(cc @karenmcgrane)

**Comment by beep** [comment]
Actually, it looks like it affects other pages as well:

http://kmg-stage.bondartscience.com/test-post/

**Comment by laras126** [comment]
Fixed! That was from some extra `p` wrappers that weren't necessary with the type of field – should be all good now.
